active/deactive & complete/continue buttons
cadwallion/trivia-host pull request #14
Opened 2021-04-22 00:27 UTC by Brian-Demon

- Added buttons to control round attributes. `Active`/`Deactive` and `Complete`/`Continue`.
- Routes updated to accommodate new buttons (control method paths)

![Capture](https://user-images.githubusercontent.com/74803363/115638028-2c4f6080-a2d7-11eb-8f94-bcab68e71cde.PNG)

2021-04-22 00:44 UTC, cadwallion requested changes

2021-04-22 00:44 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +    @game = Game.find_by(id: params[:id])
Wrong variable.

```suggestion
    @game = Game.find_by(id: params[:game_id])
```

2021-04-22 00:44 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +    @game = Game.find_by(id: params[:id])
Same problem as `activate`
```suggestion
    @game = Game.find_by(id: params[:game_id])
```

2021-04-22 00:44 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      notice.concat("actived")
Typo.
```suggestion
      notice.concat("activated")
```

2021-04-22 00:44 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      notice.concat("is already actived")
Typo.

```suggestion
      notice.concat("is already activated")
```

2021-04-22 00:44 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      notice.concat("deactived")
Typo
```suggestion
      notice.concat("deactivated")
```

2021-04-22 00:44 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      notice.concat("is already deactived")
Typo
```suggestion
      notice.concat("is already deactivated")
```

2021-04-23 21:52 UTC, cadwallion requested changes

2021-04-23 21:52 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      if @round.completed == false
Idiomatic Ruby would have this written using the `!` operator instead of equality comparison.
```suggestion
      if !@round.completed
```

2021-04-23 21:52 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      if @round.completed == true
Same as above for complete.
```suggestion
      if @round.completed
```

2021-04-23 21:52 UTC, cadwallion commented on app/views/games/show.html.erb
> +    <% if round.active == false %>
More boolean comparators.
```suggestion
    <% if !round.active %>
```

2021-04-23 21:52 UTC, cadwallion commented on app/views/games/show.html.erb
> +    <% if round.completed == false %>
More boolean comparators.
```suggestion
    <% if !round.completed %>
```

2021-04-23 22:03 UTC, Brian-Demon reviewed
🤔

2021-04-23 22:27 UTC, cadwallion requested changes
Nice work on this!

2021-04-23 22:27 UTC, cadwallion commented on app/controllers/rounds_controller.rb
> +      if @round.active == false
Whoops, one more boolean comparator.
```suggestion
      if !@round.active
```

2021-04-23 22:32 UTC, cadwallion approved these changes
👍🏻

2021-04-23 22:34 UTC, merged